### ISSUE TITLE
WARN  Crawler : AddRecursive DoItemAdd failed

### ISSUE THREAD

**Issue by jscott1277** [jscott1277/SitecoreAzureSearchProvider#21]
7056 20:48:47 WARN  Crawler : AddRecursive DoItemAdd failed - {8C56D5DE-D811-4B2E-B6E9-B2DF4C57951B}
Exception: System.InvalidOperationException
Message: Collection was modified; enumeration operation may not execute.
Source: mscorlib
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Jarstan.ContentSearch.AzureProvider.AzureUpdateContext.Commit() in C:\Users\jscott\Source\Repos\SitecoreAzureSearchProvider\Jarstan.ContentSearch.AzureProvider\AzureUpdateContext.cs:line 121
   at Jarstan.ContentSearch.AzureProvider.AzureUpdateContext.AddDocument(Object itemToAdd, IExecutionContext[] executionContexts) in C:\Users\jscott\Source\Repos\SitecoreAzureSearchProvider\Jarstan.ContentSearch.AzureProvider\AzureUpdateContext.cs:line 79
   at Jarstan.ContentSearch.AzureProvider.AzureUpdateContext.AddDocument(Object itemToAdd, IExecutionContext executionContext) in C:\Users\jscott\Source\Repos\SitecoreAzureSearchProvider\Jarstan.ContentSearch.AzureProvider\AzureUpdateContext.cs:line 70
   at Azure.ContentSearch.AzureProvider.AzureIndexOperations.Add(IIndexable indexable, IProviderUpdateContext context, ProviderIndexConfiguration indexConfiguration) in C:\Users\jscott\Source\Repos\SitecoreAzureSearchProvider\Jarstan.ContentSearch.AzureProvider\AzureIndexOperations.cs:line 88
   at Jarstan.ContentSearch.AzureItemCrawler.DoAdd(IProviderUpdateContext context, SitecoreIndexableItem indexable) in C:\Users\jscott\Source\Repos\SitecoreAzureSearchProvider\Jarstan.ContentSearch\AzureItemCrawler.cs:line 305
   at Sitecore.ContentSearch.HierarchicalDataCrawler`1.CrawlItem(T indexable, IProviderUpdateContext context, CrawlState`1 state)

**Comment by jscott1277** [comment]
2-3 of these errors occur each time I index.
